title: Bubble
email: hexsixology@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  小六家的藏宝图
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hexsix.me" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: hexsixology
github_username:  hexsix

# Build settings
theme: jekyll-theme-hacker
plugins:
  - jekyll-paginate
highlighter: rouge
paginate: 6
paginate_path: "/page:num/"
exclude: ["README.md", "LISENSE"]

markdown: kramdown
mathjax: true
